### ISSUE TITLE
Preencher lista de filmes preferidos.

### ISSUE THREAD

**Issue by leoSatoImpacta** [leoSatoImpacta/gcm-impacta#1]
Por favor preencher a lista com seus filmes preferidos em **docs/filmes.md**.

Criem um novo branch, editem o arquivo e criem um PULL REQUEST depois que finalizarem.

Obrigado.

**Comment by rbacarin** [comment]
Na mesma branch ou devo criar outra ?

**Comment by sonoftruemetal** [comment]
Eu coloquei na mesma, ele dividiu as seções por integrante

**Comment by leoSatoImpacta** [comment]
Acabei de achar nos slides que deve ser feito em outro branch e depois criar um PULL REQUEST.

**Comment by rbacarin** [comment]
Feito
